apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-front
  template:
    metadata:
      labels:
        app: python-front
    spec:
      containers:
      - name: python-front
        image: jeremyvosstest.azurecr.io/aks/aks-python-app:1.9
        ports:
        - containerPort: 8082
        env:
        - name: PYTHONPATH
          value: "/agents/python"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=ec500fd4-d1b0-48e4-8bea-85d15385b671;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/;ApplicationId=4592960f-3e47-45b7-bae3-7c9e9d788943"
---
apiVersion: v1
kind: Service
metadata:
  name: python-front
spec:
  ports:
  - port: 82
    targetPort: 8082
  selector:
    app: python-front
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-front
  template:
    metadata:
      labels:
        app: node-front
    spec:
      containers:
      - name: node-front
        image: jeremyvosstest.azurecr.io/aks/aks-node-app:1.0
        ports:
        - containerPort: 3000
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=ec500fd4-d1b0-48e4-8bea-85d15385b671;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/;ApplicationId=4592960f-3e47-45b7-bae3-7c9e9d788943"
---
apiVersion: v1
kind: Service
metadata:
  name: node-front
spec:
  ports:
  - port: 81
    targetPort: 3000
  selector:
    app: node-front
  type: LoadBalancer